### ISSUE TITLE
[Confirmed] (Current Design Limitation) ("AutoFavoritePokemon": true task not a 100% success) Bot will inadvertently transfer 100% IV pokemon if "KeepMinOperator": is set to "and", in "PokemonsTransferFilter". Quick Solution: Force bot to always run AutoFavorite task right before running the Transfer task every time it is about to transfer.

### ISSUE THREAD

**Issue by Silph-Road** [NoxxDev/NecroBot#873] opened 2016-09-05 03:44 UTC
Bot will transfer 100% IV if "KeepMinOperator" operator is set to "and" --> `"KeepMinOperator": "and",`
### Current Design
This is more of a design issue.
```
    "Dratini": {
      "KeepMinCp": 700,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
```
One would expect the bot to always keep 100 IV pokemons. For the most part.. it does.

However, if the bot is setup to to keep any pokemon over a set CP and IV (`"KeepMinOperator": "and",`), the bot will work as configured, BUT, there is a serious side effect.

The bot will transfer any pokemon that does not meet the CP&IV requirements together, INCLUDING a 100IV pokemon.

### Design Issue

This is a serious design issue that will transfer a great 100 IV pokemon unintentionally due to order of task execution where `TransferDuplicatePokemonTask` and `TransferWeakPokemonTask` happen before `FavoritePokemonTask`

**Further Explanation:**
`"AutoFavoritePokemon": true` works, but just not fast enough.
Usually it will run when you start the bot, or when it resets.
The problem is that transfer task runs after each catch ("TransferDuplicatePokemonOnCapture": true,). or later on if "false", but **there is no order to run autofavorite task before running transfer task,** regardless of when it transfers. 
So, what happens is that the Pokemon gets transferred before it can get AutoFavorited based on the `"FavoriteMinIvPercentage": 90.0,` value.

### Your config.json
```
Default
But set 
`"KeepMinOperator": "and",`

```

### Steps to Reproduce

Set   `"KeepMinOperator": "and",` in `"PokemonsTransferFilter": {` for test pokemon species. 
Set the CP/IV for test pokemon species.
The bot will catch a pokemon that is **under the CP** limit but **over the IV** limit.
Watch bot transfer the pokemon that is over `"KeepMinIvPercentage": 90` including 100 IV pokemons.

**For Example:**
`"FavoriteMinIvPercentage": 10.0 `
`"AutoFavoritePokemon": true`
`"TransferDuplicatePokemonOnCapture": true.` <-- most realistic setting, as most real human players transfer immediately, especially now after the new appraisal feature in the latest app that can tell you IV range of pokemon upon capture.

```
    "Pidgey": {
      "KeepMinCp": 700,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 10.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"

```
The bot will not favorite over the selected `"FavoriteMinIvPercentage": 10.0 ` value. and will transfer. 

This way you can test without having to wait for a 100% pokemon.

EDIT: further elaborated "Steps to Reproduce."

### Other Information
Version: 9.7
Windows Version:10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): favorite and transfer

### Solution

I have a simple and fast fix, if someone can implement it into the bot.

If the bot can **immediately** favorite a pokemon it just caught if it meets the  `"FavoriteMinIvPercentage": 90.0,` value and always set `"AutoFavoritePokemon": true,`. 
We can avoid any high IV transfers.

The key is to force the bot to run autofavorite task **before** the transfer task, every time it is about to run transfer task.
This will protect the high IV pokemon from being transferred.

Thanks.

@NoxxDev 
@jjskuld 
@mo0ojava 
@samuraitruong 

Notes: `"PrioritizeIvOverCp": true,` has no impact as it is unrelated and is superseded by the config in `"PokemonsTransferFilter": {`

**Comment by zsatanxz** [comment] 2016-09-05 04:34
I'm set tranfer dragonite cp 2500+ iv 89...?

"TransferWeakPokemon": true,
"TransferDuplicatePokemon": true,
"TransferDuplicatePokemonOnCapture": true,
"EvolveAboveIvValue": 95.0,
"EvolveAllPokemonAboveIv": false,
"EvolveAllPokemonWithEnoughCandy": true,
"EvolveKeptPokemonsAtStorageUsagePercentage": 10.0,
"KeepPokemonsThatCanEvolve": false,
"KeepMinCp": 1250,
"KeepMinIvPercentage": 95.0,
"KeepMinLvl": 6,
"KeepMinOperator": "or",
"UseKeepMinLvl": true,
"PrioritizeIvOverCp": false,
"KeepMinDuplicatePokemon": 1,
"UsePokemonToNotCatchFilter": false,
"UsePokemonSniperFilterOnly": false,
"DumpPokemonStats": false

**Comment by zsatanxz** [comment] 2016-09-05 04:38
I'm chang set tranfer snorlax cp 2400 iv 91


"TransferWeakPokemon": false,
"TransferDuplicatePokemon": true,
"TransferDuplicatePokemonOnCapture": true,
"EvolveAboveIvValue": 95.0,
"EvolveAllPokemonAboveIv": false,
"EvolveAllPokemonWithEnoughCandy": true,
"EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
"KeepPokemonsThatCanEvolve": false,
"KeepMinCp": 1550,
"KeepMinIvPercentage": 95.0,
"KeepMinLvl": 25,
"KeepMinOperator": "and",
"UseKeepMinLvl": false,
"PrioritizeIvOverCp": true,
"KeepMinDuplicatePokemon": 1,
"UsePokemonToNotCatchFilter": false,
"UsePokemonSniperFilterOnly": false,
"DumpPokemonStats": false

**Comment by zsatanxz** [comment] 2016-09-05 04:41
I'm use usenearactionrandom true

**Comment by Silph-Road** [comment] 2016-09-05 04:56
@zsatanxz your setting will have no effect on the issue reported.

The issue will only occur for pokemons listed in "PokemonsTransferFilter"
Such as:
```
"PokemonsTransferFilter": {
 "Dratini": {
      "KeepMinCp": 700,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
```
The above setting will do the following actions:
CP 600 Lvl 18 IV 70 ---> Transferred
CP 750 Lvl 21 IV 85 ---> Kept
CP 1000 Lvl 18 IV 70 ---> Transferred
CP 600 Lvl 18 IV 100 ---> Transferred

The problem is that 100IV is more valuable, but the filter is not designed that way. 
If you have autofavorite turned on, it will favorite it and block it from being transferred. 
This will only happen if the auto favorite task runs before transfer task is run, everytime the bot runs the transfer task. Thus, it will be favorited before the transfer can occur.

Note: This only occurs if you have set "KeepMinOperator": to **"and"** in "PokemonsTransferFilter": { for specific Pokemon species.

**Comment by Brazuca87** [comment] 2016-09-05 07:53
Not sure how this is an issue... You told the bot that your pokemon needs to be lvl 20 AND 700 CP AND min IV 80%

**Comment by Silph-Road** [comment] 2016-09-05 08:08
@Brazuca87 hmm.... as i stated....

> This is more of a design issue.

> This is a serious design issue that will transfer a great 100 IV pokemon unintentionally due to the filter design.

This is not a "funcational" issue, not sure how I could have been more clearer?

Do you not see that a 100 IV pokemon regardless of the CP is something that is very rare?


**Answer this question?**
Do you want to loose a 699 CP pokemon with 100 IV, just because your setting was set to CP700 and IV90.
Just because the current design limitations, do not include an IV override, doesn't mean its not an "issue".
Most of the time its a CP XX pokemon with 90%+ IV that is one power up away from the current filter settings.

100% IV is rare and even if its a CP10, its valuable for collectors and very good for bubble strat.

**The fix is simple too, just force a autofavorite task right before the transfer task is run.**

You can call it an improvement?

**Comment by DragonBlazer** [comment] 2016-09-05 09:15
@Silph-Road @NoxxDev 
This is a great improvement! I also have the CP and IV filter on. 
I lost a 100% Dratini, I had auto favorite on too. But I saw it being transferred and it was so depressing.

Please make the bot favorite before it starts to transferring Pokémon's.

**Comment by Brazuca87** [comment] 2016-09-05 09:19
Sorry, I dont see how creating poor settings is a design issue. If you want to NOT have a specific IV transferred, just make sure to favorite them. That's what the settings are for...

**Comment by Silph-Road** [comment] 2016-09-05 09:21
lmao, so you want someone to watch the bot catch every pokemon and then log in phone or use visualizer to favorite them, before the bot transfers them? why do we even have the autofavorite setting then?

**Comment by Silph-Road** [comment] 2016-09-05 09:21
@Brazuca87 

lmao, so you want someone to watch the bot catch every pokemon and then log in phone or use visualizer to favorite them, before the bot transfers them? why do we even have the autofavorite setting then?

**Comment by DragonBlazer** [comment] 2016-09-05 09:23
@Silph-Road Exactly!, 
@Brazuca87 what is the point of the autofavorite? if it cant auto-favorite the pokemon, until its too late?

**Comment by DragonBlazer** [comment] 2016-09-05 09:32
@Brazuca87 you can not expect someone to wait to see that a Pokémon is caught that is above a specific IV and then "manually" favorite them! That's so ridiculous!

**Hence, the devs thought up "Auto"Favorite: TRUE......................**
and gave us "FavoriteMinIvPercentage":,

You say:
> "Sorry, I dont see how creating poor settings is a design issue." 

Is it really Poor settings? 
or 
Is it the poor design? that does not auto favorite a pokemon in time?

**Comment by Silph-Road** [comment] 2016-09-05 09:38
@DragonBlazer you nailed it!
"AutoFavoritePokemon" and "FavoriteMinIvPercentage" are global settings and should **supersede/precede** any transfer task.

**Comment by Brazuca87** [comment] 2016-09-05 10:02
I still fail to see where he ever mentioned that he has autofavorite on, and that it failed to fav his pokemon, but whatever... :)

**Comment by Silph-Road** [comment] 2016-09-05 10:06
@Brazuca87 its in the title.... and.... all over this page, lol

The first mention:
> If the bot can immediately favorite a pokemon it just caught if it meets the "FavoriteMinIvPercentage": 90.0, value and always set "AutoFavoritePokemon": true,.
> We can avoid any high IV transfers.
> 
> The key is to force the bot to run autofavorite task before the transfer task, every time it is about to run transfer task.
> This will protect the high IV pokemon from being transferred.

**Comment by Brazuca87** [comment] 2016-09-05 10:08
You never mentioned you have it on, you are just saying doing that is the solution. Which I couldnt agree more, that is the solution...

But then again, if the problem is that it's not favoriting the pokemon, doesnt matter what you have for other settings anyways, if it's and, or, nothing, etc....

**Comment by zsatanxz** [comment] 2016-09-05 10:10
i'm set 
 "PokemonConfig": {
    "EvolveAboveIvValue": 95.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": true,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 10.0,
    "KeepPokemonsThatCanEvolve": false,
    "KeepMinCp": 1500,
    "KeepMinIvPercentage": 90.0,
    "KeepMinLvl": 20,
    "KeepMinOperator": "and",
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": false,
    "KeepMinDuplicatePokemon": 1,
    "UsePokemonToNotCatchFilter": false,
    "UsePokemonSniperFilterOnly": false,
    "DumpPokemonStats": false

**Comment by Silph-Road** [comment] 2016-09-05 10:15
@Brazuca87 It does. cuz the auto favorite works, but just not fast enough. 
Usually it will run when you start the bot, or when it resets.
The problem is that transfer task runs after each catch `("TransferDuplicatePokemonOnCapture": true,)`.

So, if you have `"KeepMinOperator": "and"`, it will get transferred before it can be Auto Favorited.

Thus, I state many times.. that autofavorite task needs to run every-time the transfer task runs and the key is that it needs to run before the transfer task, so that it can favorite the pokemon before it gets transferred.

**Comment by Silph-Road** [comment] 2016-09-05 10:19
let me incorporate that into the main post. So, that its more clearer for everyone.

**Comment by DragonBlazer** [comment] 2016-09-05 10:31
The "AutoFavoritePokemon" task can also run right after bot successfully catches a Pokémon.

**Comment by Silph-Road** [comment] 2016-09-05 10:33
@DragonBlazer Yes, it can, that would also work.
As long as it runs before the transfer task runs, it will work perfectly.

**Comment by youverena** [comment] 2016-09-05 13:17
same config : 
    "FavoriteMinIvPercentage": 99.0,
    "AutoFavoritePokemon": true,
    "KeepMinCp": 2000,
    "KeepMinIvPercentage": 99.0,
    "KeepMinLvl": 1,
    "KeepMinOperator": "or",
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": true,
    "KeepMinDuplicatePokemon": 1,

[18:56:26] Dratini	- CP: 219  IV: 96.48%   [Best CP: 533  IV: 100.00%] (Candies: 704)
[18:56:50] Cubone	- CP: 377  IV: 44.35%   [Best CP: 161  IV: 87.27%] (Candies: 61)
[18:57:06] Amount of Pokemon Seen: 72/151, Amount of Pokemon Caught: 71/151
[18:57:07] 100% perfect Dratini (CP 533) *favorited*.

[19:12:32] Psyduck	- CP: 248  IV: 42.61%   [Best CP: 422  IV: 47.81%] (Candies: 14)
[19:12:52] Lapras	- CP: 1447  IV: 100.00%   [Best CP: 492  IV: 100.00%] (Candies: 39)
[19:13:12] Amount of Pokemon Seen: 73/151, Amount of Pokemon Caught: 72/151

**Comment by Silph-Road** [comment] 2016-09-05 13:23
@youverena no, not the same config:
Your config:

> "KeepMinOperator": "or",

Test config:
`"KeepMinOperator": "and",`

**Comment by Silph-Road** [comment] 2016-09-05 13:32
@youverena 

If anyone wants to test, simply change your settings to the following:

`"FavoriteMinIvPercentage": 10.0 `
`"AutoFavoritePokemon": true`
`"TransferDuplicatePokemonOnCapture": true.` <-- most realistic setting, as most real human players transfer immediately, especially now after the new appraisal feature in the latest app that can tell you IV range of pokemon upon capture.

```
    "Pidgey": {
      "KeepMinCp": 700,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 10.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"

```
The bot will not favorite anything over the selected `"FavoriteMinIvPercentage": 10.0 ` value. and will transfer. 

This way you can test without having to wait for a 100% pokemon.

**Comment by Silph-Road** [comment] 2016-09-05 13:44
For the devs:

`TransferDuplicatePokemonTask `<-- all instances of this task should be preceded with `FavoritePokemonTask`.

For example:
```
            if (_session.LogicSettings.UseNearActionRandom)
            {
                HumanRandomActionTask.Execute(_session, cancellationToken).Wait(cancellationToken);
            }
            else
            {
                if (_session.LogicSettings.EvolveAllPokemonAboveIv || _session.LogicSettings.EvolveAllPokemonWithEnoughCandy
                    || _session.LogicSettings.UseLuckyEggsWhileEvolving || _session.LogicSettings.KeepPokemonsThatCanEvolve)
                    EvolvePokemonTask.Execute(_session, cancellationToken).Wait(cancellationToken);
                if (_session.LogicSettings.AutomaticallyLevelUpPokemon)
                    LevelUpPokemonTask.Execute(_session, cancellationToken).Wait(cancellationToken);
                if (_session.LogicSettings.UseLuckyEggConstantly)
                    UseLuckyEggConstantlyTask.Execute(_session, cancellationToken).Wait(cancellationToken);
                if (_session.LogicSettings.UseIncenseConstantly)
                    UseIncenseConstantlyTask.Execute(_session, cancellationToken).Wait(cancellationToken);
                if (_session.LogicSettings.TransferDuplicatePokemon)
                    TransferDuplicatePokemonTask.Execute(_session, cancellationToken).Wait(cancellationToken);
                if (_session.LogicSettings.TransferWeakPokemon)
                    TransferWeakPokemonTask.Execute(_session, cancellationToken).Wait(cancellationToken);
                if (_session.LogicSettings.RenamePokemon)
                    RenamePokemonTask.Execute(_session, cancellationToken).Wait(cancellationToken);
                if (_session.LogicSettings.AutoFavoritePokemon)
                    FavoritePokemonTask.Execute(_session, cancellationToken).Wait(cancellationToken);
```
Should become:
```
            if (_session.LogicSettings.UseNearActionRandom)
            {
                HumanRandomActionTask.Execute(_session, cancellationToken).Wait(cancellationToken);
            }
            else
            {
                if (_session.LogicSettings.AutoFavoritePokemon)
                    FavoritePokemonTask.Execute(_session, cancellationToken).Wait(cancellationToken);
                if (_session.LogicSettings.EvolveAllPokemonAboveIv || _session.LogicSettings.EvolveAllPokemonWithEnoughCandy
                    || _session.LogicSettings.UseLuckyEggsWhileEvolving || _session.LogicSettings.KeepPokemonsThatCanEvolve)
                    EvolvePokemonTask.Execute(_session, cancellationToken).Wait(cancellationToken);
                if (_session.LogicSettings.AutomaticallyLevelUpPokemon)
                    LevelUpPokemonTask.Execute(_session, cancellationToken).Wait(cancellationToken);
                if (_session.LogicSettings.UseLuckyEggConstantly)
                    UseLuckyEggConstantlyTask.Execute(_session, cancellationToken).Wait(cancellationToken);
                if (_session.LogicSettings.UseIncenseConstantly)
                    UseIncenseConstantlyTask.Execute(_session, cancellationToken).Wait(cancellationToken);
                if (_session.LogicSettings.TransferDuplicatePokemon)
                    TransferDuplicatePokemonTask.Execute(_session, cancellationToken).Wait(cancellationToken);
                if (_session.LogicSettings.TransferWeakPokemon)
                    TransferWeakPokemonTask.Execute(_session, cancellationToken).Wait(cancellationToken);
                if (_session.LogicSettings.RenamePokemon)
                    RenamePokemonTask.Execute(_session, cancellationToken).Wait(cancellationToken);
```

AND
```
                        if (session.LogicSettings.TransferDuplicatePokemon)
                            if (ActionRandom.Next(1, 10) > 4)
                                await TransferDuplicatePokemonTask.Execute(session, cancellationToken);
                        break;
```
Becomes:
```
                        if (session.LogicSettings.TransferDuplicatePokemon)
                            if (ActionRandom.Next(1, 10) > 4)
                                await FavoritePokemonTask.Execute(session, cancellationToken);
                                await TransferDuplicatePokemonTask.Execute(session, cancellationToken);
                        break;
```

Something like the two examples mentioned above.

**Comment by samuraitruong** [comment] 2016-09-05 13:51
not follow this issue? any dev work need?

**Comment by Silph-Road** [comment] 2016-09-05 13:54
@samuraitruong Yes.
The `FavoritePokemonTask `must execute before any `TransferDuplicatePokemonTask` and `TransferWeakPokemonTask`

If not, it willtransfer pokemon that did not get favorited and should have based on:
```
    "FavoriteMinIvPercentage": 90.0,
    "AutoFavoritePokemon": true,
```

**Comment by Silph-Road** [comment] 2016-09-05 13:57
@samuraitruong do you follow this issue now? any questions?

**Comment by Silph-Road** [comment] 2016-09-05 14:11
@samuraitruong the simplest way would be to add/execute the 
`FavoritePokemonTask` in the beginning of these files:

- "TransferDuplicatePokemonTask.cs"
- "TransferPokemonTask.cs"
- "TransferWeakPokemonTask.cs"

**Comment by Silph-Road** [comment] 2016-09-05 14:35
@samuraitruong 
edit: no need to modify.
- "TransferPokemonTask.cs"
Need it to stay same for manual transfers of pokemons that were unfavorited via pokeease/visualizer.

**Comment by youverena** [comment] 2016-09-05 17:41
@Silph-Road my bad but i think we have the same problem... correct me if I’m wrong
the bot transfers my Lapras - CP: 1447 IV: 100.00%, it get transferred before it can be auto favorited,,,

**Closed** 2016-09-05 19:20 UTC

**Comment by Brazuca87** [comment] 2016-09-05 20:41
@youverena @Silph-Road 
As I said, it's not an issue particular to `"KeepMinOperator": "and",`, doesn't matter what you have for that setting, really. It's just that it was more clear when you have that setting on.

**Comment by Silph-Road** [comment] 2016-09-05 22:45
@Brazuca87 
Nope, it does matter what you have for that setting.
Ill try to clarify it.

For the front end user:

- The **Issue** is that bot will transfer 100IV Pokemon if `KeepMinOperator": "and"` and CP does not meet limit, otherwise it "might not". 
- The **Reason** is that its designed that way and by design the AutoFavorite task runs after Transfer, so the pokemon gets transferred everytime if `KeepMinOperator": "and"`.
- The **Solution** is to run AutoFavorite task before Transfer tasks.

Plus, without pointing out the `KeepMinOperator": "and"`, no one would be able understand the issue, or be able to replicate it 100%. 

To the front end user they will only see that when they have `KeepMinOperator": "and"` they loose 100% IV if CP limit is not met and don't realize that AutoFavorite did not work in time as it runs after the transfer task and will happen 100% of the time if `KeepMinOperator": "and"`.

**Comment by Silph-Road** [comment] 2016-09-05 22:47
@Brazuca87 
In relation to @youverena 
There are three reasons (based on the config provided) that the Lapras should not have been transferred.

1. The Lapras met the `"FavoriteMinIvPercentage": 99.0,`
2. The Lapras met the global transfer requirement `"KeepMinIvPercentage": 99.0,` with `"KeepMinOperator": "or",`
3. The Lapras should have been kept even if `"KeepMinOperator": was "and",` as `"PrioritizeIvOverCp": true,`

> same config :
> "FavoriteMinIvPercentage": 99.0,
> "AutoFavoritePokemon": true,
> "KeepMinCp": 2000,
> "KeepMinIvPercentage": 99.0,
> "KeepMinLvl": 1,
> "KeepMinOperator": "or",
> "UseKeepMinLvl": false,
> "PrioritizeIvOverCp": true,
> "KeepMinDuplicatePokemon": 1,

`[19:12:52] Lapras - CP: 1447 IV: 100.00% Best CP: 492 IV: 100.00%`

So, now you can tell @youverena and I, why was the Lapras transferred?

Was it because the AutoFavorite did not protect it or the transfer settings did not enforce properly?
or both??

_Either one would/should have stopped the transfer...._


(@youverena I have not tested your scenario to be able to give a definite reason, why the Lapras got transferred, as you can see there are 3 reasons why it should not have happened..
Regardless of that, the devs have made changes as requested, that will in a way prevent it from happening again.)

**Comment by Silph-Road** [comment] 2016-09-05 22:58
It would be beneficial for you to troubleshoot reported bot issues, such as the one listed by @youverena and others, instead of focusing on what you believe the issue is? or if its an issue or design or if its a non-issue....

> In short, the bot did exactly what you asked... Where is the issue?

In the end the solution that was implemented is what you agreed with isn't it? as it takes care of multiple scenarios....

I am waiting for @Brazuca87 to again repeat how `"KeepMinOperator": and` doesn't matter.....
