### ISSUE TITLE
Bot crashing on start with valid Google ApiKey in config

### ISSUE THREAD

**Issue by Delta1977** [NoxxDev/NecroBot#862] opened 2016-09-04 18:17 UTC
With valid google APIkey in Config the bot crashed at start, without key its working:

Unbehandelte Ausnahme: System.InvalidOperationException: Die Sequenz enthält keine Elemente.
   bei System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   bei PoGo.NecroBot.Logic.Model.Google.GoogleWalk..ctor(GoogleResult googleResult) in C:\_git\NecroBot\PoGo.NecroBot.Logic\Model\Google\GoogleWalk.cs:Zeile 19.
   bei PoGo.NecroBot.Logic.Model.Google.GoogleWalk.Get(GoogleResult googleResult) in C:\_git\NecroBot\PoGo.NecroBot.Logic\Model\Google\GoogleWalk.cs:Zeile 60.
   bei PoGo.NecroBot.Logic.Model.Google.Teste.Testar(ISession session) in C:\_git\NecroBot\PoGo.NecroBot.Logic\Model\Google\Teste.cs:Zeile 15.
   bei PoGo.NecroBot.CLI.Program.Main(String[] args) in C:\_git\NecroBot\PoGo.NecroBot.CLI\Program.cs:Zeile 164.

**Comment by seouljah760** [comment] 2016-09-04 18:42
# **Utilize this format when having config issues:**

### Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check. 

## YES or NO

### Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead. 

## YES or NO

### Have you searched the wiki? Is it unclear? Does it not have what you're looking for?

## YES or NO. Explain

## Expected Behavior

Pokemon are transferring based on config

## Actual Behavior

Pokemon are NOT transferring based on config

## Your config.json

www.pastebin.com/yourconfig.json

##  Steps to Reproduce

insert pertinent information here

## Other Information

Version: 0.9.7
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): transfer

insert pics here

-----------------------------------------------------------------------------------------------------------------

**Comment by seouljah760** [comment] 2016-09-04 18:43
Also change the translation to English so we can read it.

**Comment by mo0ojava** [comment] 2016-09-04 20:28
I actually fixed this bug (just remove the call to superfluous Teste in Program.cs as well as Teste.cs). Haven't verified that this doesn't have adversary side-effects though since I haven't used Google Walk etc for a while. Figured it needs testing before committing.

**Comment by mo0ojava** [comment] 2016-09-04 20:31
Maybe @samuraitruong or @jjskuld knows what purpose Teste serve(d)? A relic?

**Comment by jjskuld** [comment] 2016-09-05 04:25
Bug caused by empty Google navigation result being cached (when over quota for example).  Fixed in a58b8dc95d51f9e7b1d0fc0aa0d2128d3c3dd143

**Closed** 2016-09-05 04:26 UTC

**Comment by jjskuld** [comment] 2016-09-06 06:09
I have no idea what that test file is used for, but when Google API is not working then it causes issues.  FYI I removed the test file already.
