### ISSUE TITLE
[Issue] Fix protocol API. Current public Rocket API / FeroxDev is completely broken.

### ISSUE THREAD

**Issue by WinterMoxRZ** [NoxxDev/NecroBot#265] opened 2016-08-19 15:27 UTC
I give you a hint:

//static for now
sig.Unk22 = ByteString.CopyFrom(new byte[16] { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F });

In issue "#146 update pogoprotos" thekjohn already brought this somewhat up but that's not all. There are others issues.

Most critical issue is broken low level protocol API and Unk22 or should I say SESSION_ID or SessionHash as others have named it is example of those issues.

Then there are also critical higher level protocol API issues but right now some of them can be handled with workarounds. None the less also these issues should be fixed on Rocket API. These issues include such things as configuring PoGO avatar, trainer naming, pop-up messages, collecting badges etc.

Right now adding such features as KillSwitch + CatchEscapeExceeded etc, yournavigation.org + Google Maps routing, Costura.Fody, etc is complete nonsense!

Niantic can and does identify every 3rd party application which uses BROKEN protocol API. Hence Niantic has and will identify every Google or PTC account used with these tools.

Niantic could ban every 3rd party user in few seconds or at most in minute or so. Why they don't do that? Well most of you already know the answer, because they don't want to give out how people end up in ban waves.

Right thing to do at the moment would be to dig in authentic PoGO client traffic either using MITM or other methods and rewrote Rocket API in away which emulates 100% accurately official PoGO client.

My 5c.

**Comment by zapahacks** [comment] 2016-08-19 15:50
Do you know is there any other bot that have managed to correct/implement this? :)
Thanks by the way

**Comment by TLBM** [comment] 2016-08-19 15:52
Thats seems a good point which should be looked into.

**Comment by male2961** [comment] 2016-08-19 16:02
whats the used? hehe..

**Comment by WinterMoxRZ** [comment] 2016-08-19 18:55
@zapahacks 
Going through every NecroBot or Rocket API fork isn't my cup of tea. What I do know is that if someone pulled or cloned PokeMobBot 2.0.2 from Git then that compile also has that static SESSION_ID.

**Comment by WinterMoxRZ** [comment] 2016-08-19 19:02
Now here is part two of my hints.

As some people may say "pics or it didn't happen" here's two pictures.

This is from official client X:

![01](https://cloud.githubusercontent.com/assets/21127256/17820973/048475ec-6658-11e6-8311-a7bf1ce82fcb.gif)


This is from public Rocket API:

![02](https://cloud.githubusercontent.com/assets/21127256/17820988/0c886668-6658-11e6-92f9-65b61c04b3c2.gif)

These are from same request, can you spot the difference?

Now this is my 10c.

**Comment by vfuyong** [comment] 2016-08-19 19:29
This is urgent!

**Comment by popoche** [comment] 2016-08-19 20:03
It really seem to be the cause of the perma bans !

**Comment by TheTravelingTrainer** [comment] 2016-08-19 20:23
don't forget we haven't worked out request ids!.. Another easy find for a ban..

I've got quite a few variation of bots and apis (all custom) to see whats causing specific bans.. I would say the main thing between them that have been band is the static unknown22 and the request ids are randomly generated (Well, correctly generated in their pattern, but not idea how they are creating the hidword part of the int64

**Comment by PocketMobsters** [comment] 2016-08-19 20:33
While I can't speak for Noxx, we've fixed it in ours (unfortunately we had to remove our GitHub stuff for the next 10 business days while we wait to see if Necro gets a court-ordered DMCA). It's not that difficult, he can message us if he wants the magic.

**Comment by popoche** [comment] 2016-08-19 22:13
@PocketMobsters Are you sure its fixed in yours ? I used it with very slow human config and still got a permaban.

**Comment by WinterMoxRZ** [comment] 2016-08-19 23:09
@PocketMobsters
Well I haven't looked what is packaged in to PokeMobBot pre-compiled binaries so . . .
What was in Git around 2.0.2 didn't have any major changes related to problem with public Rocket API.

**Comment by NoxxDev** [comment] 2016-08-20 17:25
Fixed https://github.com/NoxxDev/NecroBot-Rocket-API/commit/6bc1672760921b5aed812b2bd799936aa23726f6

**Closed by NoxxDev** 2016-08-20 17:25 UTC
